name: PHPUnit

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  phpunit-nodb:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: [ '7.3', '7.4', '8.0' ]
    steps:
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype,curl,dom,fileinfo,gd,iconv,intl,json,mbstring,oci8,openssl,pdo_sqlite,posix,sqlite,xml,zip
          tools: phpunit:9.5.4
          coverage: none
      - name: PHPUnit
        env:
          NOCOVERAGE: true
          TEST_SELECTION: NODB
        run: bash autotest.sh sqlite

  phpunit-oci8:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-versions: [ '7.4' ]
        databases: [ 'oci' ]

    name: php${{ matrix.php-versions }}-${{ matrix.databases }}

    services:
      oracle:
        image: deepdiver/docker-oracle-xe-11g # "wnameless/oracle-xe-11g-r2"
        ports:
          - "1521:1521"

    steps:
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype,curl,dom,fileinfo,gd,iconv,intl,json,mbstring,oci8,openssl,pdo_sqlite,posix,sqlite,xml,zip
          tools: phpunit:8.5.2
          coverage: none

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=1521 --database-user=autotest --database-pass=owncloud --admin-user admin --admin-pass admin
          php -f index.php

      - name: PHPUnit
        working-directory: tests
        run: phpunit --configuration phpunit-autotest.xml --group DB,SLOWDB
